# Generated by Django 6.0.6 on 2026-06-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieCounter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfomodel',
            name='brm',
            field=models.FloatField(null=True),
        ),
    ]
