# Generated by Django 6.0.6 on 2026-06-17 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CalorieCounter', '0002_basicinfomodel_brm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicinfomodel',
            old_name='brm',
            new_name='bmr',
        ),
    ]
